<?php

/**
 * Implements hook_menu().
 */
function sonar_menu(){
  $items['admin/config/system/sonar'] = array(
    'title' => 'Sonar',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sonar_settings'),
    'access arguments' => array('administer sonar'),
    'file' => 'sonar.admin.inc',
    'description' => t('Configure Sonar settings.')
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function sonar_permission() {
  return array(
    'administer sonar' => array(
      'title' => t('Administer Sonar'),
      'description' => t('Perform administration tasks for Sonar.'),
    ),
  );
}

/**
 * Implements hook_css_alter().
 */
function sonar_css_alter(&$css) {
  static $once;
  if(sonar_is_enabled() && $scss = sonar_files($css)){
    if (!isset($once)) {
      $once = 1;
      $handler = sonar_get_handler('adapter', sonar_active_adapter());
      if($files = $handler->build($scss)){
        foreach($files as $file){
          $css[$file['data']] = $file;
        }
      }
    }
  }
}

/**
 * Picks all Sass files from an array of stylesheets.
 *
 * @param $css
 *   An array of all CSS items (files and inline CSS) being requested on the page.
 *
 * @return
 *   The extracted files as an array.
 */
function sonar_files(&$css) {
  $files = array();
  foreach ($css as $key => $file) {
    if ($file['type'] == 'file') {
      $extension = drupal_substr($file['data'], -5);
      if (in_array($extension, array('.scss', '.sass'))) {
        $file['syntax'] = $extension == '.scss' ? 'scss' : 'sass';
        $files[$key] = $file;
        // Remove from page render.
        unset($css[$key]);
      }
    }
  }

  // Inject custom variables.
  _sonar_vars($files);

  return $files;
}

/**
 * Get any declared custom variables and add them to the files list.
 */
function _sonar_vars(&$files){
  $hook = 'sonar_var';
  if ($cache = cache_get($hook)) {
    $vars = $cache->data;
  }
  else{
    // Allow others to add their own variables.
    $vars = array();
    foreach (module_implements($hook) as $module) {
      // Calling all modules implementing hook_hook_name and
      // Returning results than pushing them into the $result array:
      $vars += module_invoke($module, $hook);
    }
     // Let the themes play too, because pre render is a very themey thing.
    foreach ($GLOBALS['base_theme_info'] as $base) {
      $function = $base->name . '_' . $hook;
      if (function_exists($function)) {
        $vars += $function();
      }
    }
    $function = $GLOBALS['theme'] . '_' . $hook;
    if (function_exists($function)) {
      $vars += $function();
    }
    // Allow others to alter the variables.
    drupal_alter($hook, $vars);

    // Cache results.
    cache_set($hook, $vars, 'cache');
  }

  if($page_vars = sonar_add_var()){
    $vars += $page_vars;
  }

  if(!empty($vars)){
    $count = 0;
    $options = array(
      'group' => CSS_DEFAULT,
      'every_page' => TRUE,
      'weight' => 0,
      'base_weight' => -1000,
    );
    foreach($vars as $key => $value){
      if(!is_array($value)){
        $value = array(
          'value' => $value,
        );
      }
      $value += $options;
      $value['weight'] += $value['base_weight'] + ($count * .1);
      if(is_bool($value['value'])){
        $value['value'] = $value['value'] ? 'true' : 'false';
      }
      $id = substr(drupal_hash_base64($value['group'] . $value['every_page'] . $key . $value['value']), 0, 30);
      $files['sonar_var_' . $id] = $value += array(
        'type' => 'inline',
        'data' => '$' . $key . ': ' . (string) $value['value'] . ";\n",
      );
      $count++;
    }
  }
}

/**
 * Inject a variable into the SCSS file Sonar is about to compile.
 *
 * This should only be used for single page injection. For global injection
 * please use hook_sonar_var and hook_sonar_var_alter.
 *
 * @param $name
 *   The variable name as a string.
 * @param $var
 *   An array or string. See hook_sonar_var() in sonar.api.php for more information.
 */
function sonar_add_var($name = NULL, $value = NULL){
  static $cache;
  if($name && $value){
    $cache[$name] = array(
      'value' => $value,
      'every_page' => FALSE,
    );
  }
  return $cache;
}

/**
 * Check if Sonar is enabled.
 */
function sonar_is_enabled(){
  return variable_get('sonar_status', 1);
}

/**
 * Dubug mode enabled
 */
function sonar_is_debug(){
  return variable_get('sonar_debug');
}

/**
 * Get the currently active adapter that should be used to compile the SASS.
 */
function sonar_active_adapter(){
  ctools_include('plugins');
  $plugins = ctools_get_plugins('sonar', 'adapter');
  // We do have a setting.
  if($current = variable_get('sonar_adapter')){
    // Make sure plugin is still available.
    if(isset($plugins[$current])){
      return $current;
    }
  }
  // Default to SASSquatch.
  return 'sassquatch';
}

/**
 * Get Sonar destination.
 */
function sonar_get_destination(){
  $destination = variable_get('sonar_destination');
  if(empty($destination)){
    $destination = variable_get('file_' . file_default_scheme() . '_path', conf_path() . '/files') . '/sonar';
  }
  return $destination;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function sonar_ctools_plugin_api() {
  list($module, $api) = func_get_args();

  if ($module == 'sonar' && ($api == 'plugins')) {
    return array('version' => 1.0);
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function sonar_ctools_plugin_type() {
  return array(
    'adapter' => array(
      'classes' => array('class'),
    ),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function sonar_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'sonar') {
    return "plugins/$plugin_type";
  }
}

/**
 * Get a Sonar handler.
 *
 * @param $type
 *   The plugin type.
 * @param $name
 *   The name of the plugin.
 */
function sonar_get_handler($type, $name) {
  $object_cache = drupal_static(__FUNCTION__);
  if (!isset($object_cache[$name])) {
    ctools_include('plugins');
    $class = ctools_plugin_load_class('sonar', $type, $name, 'class');
    $class = class_exists($class) ? $class : 'Sonar_'.ucfirst($type).'_Broken';
    $all_args = func_get_args();
    $args = array_slice($all_args, 2);
    $object_cache[$name] = new $class($name, $args);
  }

  return $object_cache[$name];
}
